const products = [
  {
    id: 1,
    name: "Stylish Jacket",
    price: 120,
    originalPrice: 150,
    description: "This is a stylish jacket perfect for any occasion.",
    brand: "AaryanPrints",
    offer: "50% discount",
    material: "Leather",
    category: "Kurta",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Black"],
    images: [
      { url: "https://images.meesho.com/images/products/566935952/6whya_512.avif?width=512", altText: "Stylish Jacket 1" },
      { url: "https://images.meesho.com/images/products/566935952/ay0f9_512.avif?width=512", altText: "Stylish Jacket 2" },
    ],
  },
  {
    id: 2,
    name: "White Striped Polo",
    price: 80,
    originalPrice: 100,
    description: "Classic striped polo for casual wear.",
    brand: "AJILE",
    material: "Cotton",
    category: "Polo",
    sizes: ["S", "M", "L"],
    colors: ["White", "Blue"],
    images: [
      { url: "https://placehold.co/400x500/E5E7EB/1F2937?text=Polo", altText: "Polo Shirt" },
    ],
  },
  {
    id: 3,
    name: "Purple Kurta",
    price: 60,
    originalPrice: 90,
    description: "Purple Foil Print A-line Peplum Kurta.",
    brand: "RANGMANCH",
    material: "Silk Blend",
    category: "Kurta",
    sizes: ["M", "L", "XL"],
    colors: ["Purple"],
    images: [
      { url: "https://placehold.co/400x500/E5E7EB/1F2937?text=Kurta", altText: "Purple Kurta" },
    ],
  },
  {
    id: 4,
    name: "Beige Floral Kurta",
    price: 70,
    originalPrice: 100,
    description: "Beige Watercolour Floral Print A-line Kurta.",
    brand: "RANGMANCH",
    material: "Cotton",
    category: "Kurta",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige"],
    images: [
      { url: "https://placehold.co/400x500/E5E7EB/1F2937?text=Kurta+2", altText: "Beige Floral Kurta" },
    ],
  },
  {
    id: 5,
    name: "Yellow Dress",
    price: 90,
    originalPrice: 120,
    description: "Yellow printed layered collar A-line dress.",
    brand: "MARIGOLD LANE",
    material: "Cotton Blend",
    category: "Dress",
    sizes: ["S", "M"],
    colors: ["Yellow"],
    images: [
      { url: "https://placehold.co/400x500/E5E7EB/1F2937?text=Dress", altText: "Yellow Dress" },
    ],
  },
  {
    id: 6,
    name: "Black Hoodie",
    price: 110,
    originalPrice: 140,
    description: "Casual black hoodie with front pocket.",
    brand: "UrbanVibe",
    material: "Fleece",
    category: "Hoodie",
    sizes: ["M", "L", "XL"],
    colors: ["Black"],
    images: [
      { url: "https://placehold.co/400x500/000000/FFFFFF?text=Hoodie", altText: "Black Hoodie" },
    ],
  },
  {
    id: 7,
    name: "Blue Denim Jeans",
    price: 95,
    originalPrice: 120,
    description: "Comfortable blue denim jeans for daily wear.",
    brand: "DenimPro",
    material: "Denim",
    category: "Jeans",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue"],
    images: [
      { url: "https://placehold.co/400x500/1E3A8A/FFFFFF?text=Jeans", altText: "Blue Denim Jeans" },
    ],
  },
  {
    id: 8,
    name: "Red Sports Shoes",
    price: 150,
    originalPrice: 200,
    description: "Red running shoes with lightweight design.",
    brand: "RunFast",
    material: "Synthetic",
    category: "Shoes",
    sizes: ["7", "8", "9", "10"],
    colors: ["Red"],
    images: [
      { url: "https://placehold.co/400x500/FF0000/FFFFFF?text=Shoes", altText: "Red Sports Shoes" },
    ],
  },
  {
    id: 9,
    name: "White Sneakers",
    price: 130,
    originalPrice: 160,
    description: "Classic white sneakers for everyday wear.",
    brand: "SneakPeak",
    material: "Canvas",
    category: "Shoes",
    sizes: ["6", "7", "8", "9"],
    colors: ["White"],
    images: [
      { url: "https://placehold.co/400x500/FFFFFF/000000?text=Sneakers", altText: "White Sneakers" },
    ],
  },
  {
    id: 10,
    name: "Green T-Shirt",
    price: 50,
    originalPrice: 70,
    description: "Comfortable green cotton t-shirt.",
    brand: "EcoWear",
    material: "Cotton",
    category: "T-Shirt",
    sizes: ["S", "M", "L"],
    colors: ["Green"],
    images: [
      { url: "https://placehold.co/400x500/008000/FFFFFF?text=T-Shirt", altText: "Green T-Shirt" },
    ],
  },
  {
    id: 11,
    name: "Brown Leather Belt",
    price: 40,
    originalPrice: 60,
    description: "Stylish brown leather belt.",
    brand: "LeatherWorks",
    material: "Leather",
    category: "Belt",
    sizes: ["M", "L", "XL"],
    colors: ["Brown"],
    images: [
      { url: "https://placehold.co/400x500/8B4513/FFFFFF?text=Belt", altText: "Brown Leather Belt" },
    ],
  },
  {
    id: 12,
    name: "Grey Hoodie",
    price: 105,
    originalPrice: 130,
    description: "Comfortable grey hoodie with hood.",
    brand: "UrbanVibe",
    material: "Fleece",
    category: "Hoodie",
    sizes: ["M", "L", "XL"],
    colors: ["Grey"],
    images: [
      { url: "https://placehold.co/400x500/A9A9A9/000000?text=Hoodie", altText: "Grey Hoodie" },
    ],
  },
  {
    id: 13,
    name: "Pink Skirt",
    price: 80,
    originalPrice: 110,
    description: "Lightweight pink skirt for casual wear.",
    brand: "MARIGOLD LANE",
    material: "Cotton Blend",
    category: "Skirt",
    sizes: ["S", "M", "L"],
    colors: ["Pink"],
    images: [
      { url: "https://placehold.co/400x500/FFC0CB/000000?text=Skirt", altText: "Pink Skirt" },
    ],
  },
  {
    id: 14,
    name: "Black Formal Shoes",
    price: 180,
    originalPrice: 220,
    description: "Elegant black formal shoes for men.",
    brand: "FormalStep",
    material: "Leather",
    category: "Shoes",
    sizes: ["8", "9", "10", "11"],
    colors: ["Black"],
    images: [
      { url: "https://placehold.co/400x500/000000/FFFFFF?text=Shoes", altText: "Black Formal Shoes" },
    ],
  },
  {
    id: 15,
    name: "Orange Hoodie",
    price: 115,
    originalPrice: 150,
    description: "Vibrant orange hoodie for casual style.",
    brand: "UrbanVibe",
    material: "Fleece",
    category: "Hoodie",
    sizes: ["M", "L", "XL"],
    colors: ["Orange"],
    images: [
      { url: "https://placehold.co/400x500/FFA500/000000?text=Hoodie", altText: "Orange Hoodie" },
    ],
  },
];

export default products;
